# Generated by Django 5.0.6 on 2024-06-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='img/users/'),
        ),
    ]
