# Generated by Django 5.0.6 on 2024-06-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0003_alter_fichanota_professor_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichanota',
            name='professor_disciplina',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGN.professordisciplina'),
        ),
    ]
