# Generated by Django 5.0.6 on 2024-06-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0004_alter_fichanota_professor_disciplina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['curso', 'turno', 'ano_academico']},
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano_academico',
            field=models.CharField(choices=[('1', '1º Ano'), ('2', '2º Ano'), ('3', '3º Ano'), ('4', '4º Ano'), ('5', '5º Ano')], max_length=10, verbose_name='Ano Acadêmico'),
        ),
    ]
