# Generated by Django 5.0.6 on 2024-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0005_alter_turma_options_alter_turma_ano_academico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['curso', 'ano_academico', 'turno']},
        ),
        migrations.AddField(
            model_name='fichanota',
            name='semestre',
            field=models.CharField(choices=[('1', '1º Semestre'), ('2', '2º Semestre')], default='1', max_length=20),
        ),
    ]
