# Generated by Django 5.0.6 on 2024-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0006_alter_turma_options_fichanota_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichanota',
            name='semestre',
            field=models.CharField(choices=[('1º Semestre', '1º Semestre'), ('2º Semestre', '2º Semestre')], default='1', max_length=20),
        ),
    ]
