# Generated by Django 5.0.6 on 2024-06-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0007_alter_fichanota_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(choices=[('1º Semestre', '1º Semestre'), ('2º Semestre', '2º Semestre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fichanota',
            name='semestre',
            field=models.CharField(choices=[('1º Semestre', '1º Semestre'), ('2º Semestre', '2º Semestre')], default='1º Semestre', max_length=20),
        ),
    ]
