# Generated by Django 5.0.6 on 2024-06-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0008_alter_disciplina_semestre_alter_fichanota_semestre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professordisciplina',
            unique_together={('professor', 'disciplina', 'turma')},
        ),
    ]
