# Generated by Django 5.0.6 on 2024-06-20 05:43

import SGN.validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0009_alter_professordisciplina_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichanota',
            name='avaliacao1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[SGN.validator.validar_nota], verbose_name='Avaliação 1'),
        ),
        migrations.AlterField(
            model_name='fichanota',
            name='avaliacao2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[SGN.validator.validar_nota], verbose_name='Avaliação 2'),
        ),
        migrations.AlterField(
            model_name='fichanota',
            name='exame',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[SGN.validator.validar_nota], verbose_name='Exame'),
        ),
        migrations.AlterField(
            model_name='fichanota',
            name='media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[SGN.validator.validar_nota], verbose_name='Média'),
        ),
        migrations.AlterField(
            model_name='fichanota',
            name='professor_disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGN.professordisciplina'),
        ),
        migrations.AlterField(
            model_name='fichanota',
            name='prova1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[SGN.validator.validar_nota], verbose_name='Prova 1'),
        ),
        migrations.AlterField(
            model_name='fichanota',
            name='prova2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[SGN.validator.validar_nota], verbose_name='Prova 2'),
        ),
        migrations.AlterField(
            model_name='fichanota',
            name='recurso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[SGN.validator.validar_nota], verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='fichanota',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Recurso', 'Recurso'), ('Dispensa', 'Dispensa'), ('Exame', 'Exame')], default='Não avaliado', max_length=20),
        ),
    ]
