# Generated by Django 5.0.6 on 2024-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGN', '0010_alter_fichanota_avaliacao1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichanota',
            name='prova1_ajustada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichanota',
            name='prova2_ajustada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichanota',
            name='status_finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
